/**
 * @swagger
 * components:
 *   schemas:
 *     Message:
 *       type: object
 *       required:
 *         - from
 *       properties:
 *         _id:
 *           type: string
 *           description: Message's autogenerated ID
 *         from:
 *           type: object
 *           properties:
 *             _id:
 *               type: string
 *               description: Sender's ID
 *               required: true
 *         source:
 *           type: string
 *           description: Path for message media (required and allowed only when `message` is not set)
 *         message:
 *           type: string
 *           description: Message content (required and allowed only when `source` is not set)
 *         createdAt:
 *           type: string
 *           format: date-time
 *         edited:
 *           type: string
 *           format: date-time
 */