/**
 * @swagger
 * components:
 *  schemas:
 *    User:
 *      type: object
 *      required:
 *        - username
 *        - email
 *        - password
 *      properties:
 *        _id:
 *         type: string
 *         description: User autogenerated ID
 *        username:
 *         type: string
 *         minLength: 5
 *         maxLength: 50
 *         description: Username of the User
 *        email:
 *         type: string
 *         minLength: 5
 *         maxLength: 70
 *         description: Email address of the User
 *        password:
 *         type: string
 *         minLength: 8
 *         maxLength: 1024
 *         description: User's password (maximum length of the `password` is 70 but because of password hashing is set to 1024 in User model)
 *      example:
 *        _id: 6480a22330db01f182b4646f
 *        username: Test1
 *        email: a@vp.pl
 *        password: $2b$15$B4Lr9qSun4U6wgM0865gV.5iFs8mcbDonPQwN4F3BEmWNFcbVocu.
 */